<?php
return [
  'routes' => [
    ['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
    ['name' => 'page#apps', 'url' => '/apps', 'verb' => 'GET'],
    ['name' => 'page#system', 'url' => '/system', 'verb' => 'GET'],
    ['name' => 'page#user', 'url' => '/user', 'verb' => 'GET'],
    ['name' => 'page#ops', 'url' => '/ops', 'verb' => 'GET'],
    ['name' => 'page#tools', 'url' => '/tools', 'verb' => 'GET'],
    ['name' => 'page#host', 'url' => '/host', 'verb' => 'GET'],
    ['name' => 'page#userlist', 'url' => '/userlist', 'verb' => 'POST'],
    ['name' => 'page#userlistget', 'url' => '/userlist', 'verb' => 'GET'],
    ['name' => 'Apps#listCategories', 'url' => '/appsasc', 'verb' => 'GET'],
    ['name' => 'Apps#appsinfo', 'url' => '/appsinfo', 'verb' => 'GET'],
    ['name' => 'Apps#isnoti', 'url' => '/isnoti', 'verb' => 'GET'],
    ['name' => 'Apps#islogcleaner', 'url' => '/islogcleaner', 'verb' => 'GET'],
    ['name' => 'Apps#enableapp', 'url' => '/enableapp/{who}', 'verb' => 'GET'],
    ['name' => 'Apps#disableapp', 'url' => '/disableapp/{who}', 'verb' => 'GET'],
    ['name' => 'Apps#getAppsWithUpdates', 'url' => '/appupdates', 'verb' => 'GET'],
    ['name' => 'Apps#updateapp', 'url' => '/updateapp/{who}', 'verb' => 'GET'],
    ['name' => 'Group#addgroup', 'url' => '/addgroup/{who}', 'verb' => 'GET'],
    ['name' => 'Group#deletegroup', 'url' => '/deletegroup/{who}', 'verb' => 'GET'],
    ['name' => 'System#storage', 'url' => '/storage', 'verb' => 'GET'],
    ['name' => 'System#sqlinfo', 'url' => '/sqlinfo', 'verb' => 'GET'],
    ['name' => 'System#systeminfo', 'url' => '/systeminfo', 'verb' => 'GET'],
    ['name' => 'System#widgetinfo', 'url' => '/widgetinfo', 'verb' => 'GET'],
    ['name' => 'User#deleteuser', 'url' => '/deleteuser/{who}', 'verb' => 'GET'],
    ['name' => 'User#edituser', 'url' => '/edituser/{who}', 'verb' => 'GET'],
    ['name' => 'User#newuser', 'url' => '/newuser', 'verb' => 'POST'],
    ['name' => 'User#saveuser', 'url' => '/saveuser', 'verb' => 'POST'],
    ['name' => 'User#userexists', 'url' => '/userexists/{who}', 'verb' => 'GET'],
    ['name' => 'User#notifyuser', 'url' => '/notifyuser', 'verb' => 'POST'],
    ['name' => 'User#notifygroup', 'url' => '/notifygroup', 'verb' => 'POST'],
    ['name' => 'User#usercount', 'url' => '/usercount', 'verb' => 'GET'],
    ['name' => 'tower#health', 'url' => '/tower/health', 'verb' => 'GET'],
    ['name' => 'tower#hostSummary', 'url' => '/tower/host', 'verb' => 'GET'],
    ['name' => 'tower#hostGpu', 'url' => '/tower/gpu', 'verb' => 'GET'],
    ['name' => 'tower#hostSmart', 'url' => '/tower/smart', 'verb' => 'GET'],
    ['name' => 'tower#hostFan', 'url' => '/tower/fan', 'verb' => 'GET'],
    ['name' => 'tower#fanSet', 'url' => '/tower/fan', 'verb' => 'POST'],
    ['name' => 'tower#hostChassisFan', 'url' => '/tower/chassis-fan', 'verb' => 'GET'],
    ['name' => 'tower#hostMounts', 'url' => '/tower/mounts', 'verb' => 'GET'],
    ['name' => 'tower#hostPackages', 'url' => '/tower/packages', 'verb' => 'GET'],
    ['name' => 'tower#hostProc', 'url' => '/tower/proc', 'verb' => 'GET'],
    ['name' => 'tower#hostNet', 'url' => '/tower/net', 'verb' => 'GET'],
    ['name' => 'tower#hostSystemd', 'url' => '/tower/systemd', 'verb' => 'GET'],
    ['name' => 'tower#systemdRestart', 'url' => '/tower/systemd/restart', 'verb' => 'POST'],
    ['name' => 'tower#hostCron', 'url' => '/tower/cron', 'verb' => 'GET'],
    ['name' => 'tower#containers', 'url' => '/tower/containers', 'verb' => 'GET'],
    ['name' => 'tower#containerLogs', 'url' => '/tower/containers/{name}/logs', 'verb' => 'GET'],
    ['name' => 'tower#containerInspect', 'url' => '/tower/containers/{name}/inspect', 'verb' => 'GET'],
    // Routes resolve in declaration order, so a {action} placeholder here would
    // swallow /recreate and /exec and hand them to containerAction(), which
    // rejects anything outside its allowlist with a 400. Both features were
    // dead that way. Enumerate the verbs instead: nothing can shadow a sibling.
    ['name' => 'tower#containerRecreate', 'url' => '/tower/containers/{name}/recreate', 'verb' => 'POST'],
    ['name' => 'tower#containerExec', 'url' => '/tower/containers/{name}/exec', 'verb' => 'POST'],
    [
        'name' => 'tower#containerAction',
        'url' => '/tower/containers/{name}/{action}',
        'verb' => 'POST',
        'requirements' => ['action' => 'start|stop|restart|kill'],
    ],
    ['name' => 'tower#dockerInfo', 'url' => '/tower/docker/info', 'verb' => 'GET'],
    ['name' => 'tower#dockerDf', 'url' => '/tower/docker/df', 'verb' => 'GET'],
    ['name' => 'tower#dockerEvents', 'url' => '/tower/docker/events', 'verb' => 'GET'],
    ['name' => 'tower#dockerImages', 'url' => '/tower/docker/images', 'verb' => 'GET'],
    ['name' => 'tower#imagePull', 'url' => '/tower/docker/images/pull', 'verb' => 'POST'],
    ['name' => 'tower#dockerVolumes', 'url' => '/tower/docker/volumes', 'verb' => 'GET'],
    ['name' => 'tower#dockerNetworks', 'url' => '/tower/docker/networks', 'verb' => 'GET'],
    ['name' => 'tower#stacks', 'url' => '/tower/stacks', 'verb' => 'GET'],
    [
        'name' => 'tower#stackAction',
        'url' => '/tower/stacks/{action}',
        'verb' => 'POST',
        'requirements' => ['action' => 'up|down|restart|pull|rebuild'],
    ],
    ['name' => 'tower#opsInbox', 'url' => '/tower/ops-inbox', 'verb' => 'GET'],
    ['name' => 'tower#backupRun', 'url' => '/tower/backup/run', 'verb' => 'POST'],
    ['name' => 'tower#tools', 'url' => '/tower/tools', 'verb' => 'GET'],
    ['name' => 'tower#services', 'url' => '/tower/services', 'verb' => 'GET'],
    ['name' => 'tower#hostUpdates', 'url' => '/tower/updates', 'verb' => 'GET'],
    ['name' => 'tower#hostHistory', 'url' => '/tower/history', 'verb' => 'GET'],
    ['name' => 'tower#opsTimeline', 'url' => '/tower/ops-timeline', 'verb' => 'GET'],
    ['name' => 'tower#jobs', 'url' => '/tower/jobs', 'verb' => 'GET'],
    ['name' => 'tower#job', 'url' => '/tower/jobs/{id}', 'verb' => 'GET'],
    // Distinct verb from tower#job, so the two cannot shadow each other.
    [
        'name' => 'tower#jobStart',
        'url' => '/tower/jobs/{kind}',
        'verb' => 'POST',
        'requirements' => ['kind' => 'apt-upgrade|apt-dry-run|backup|image-pull|stack-action'],
    ],
  ]
];
